command:
  - "gunicorn"
  - "main:app"
  - "-w"
  - "2"
  - "--worker-class"
  - "uvicorn.workers.UvicornWorker"

resources:
  - name: "serving-endpoint"
    serving_endpoint:
      name: "mas-b652e4f4-endpoint"
      permission: "CAN_QUERY"

env:
  - name: "SERVING_ENDPOINT_NAME"
    valueFrom: "serving-endpoint"